### ISSUE TITLE
C_START_INSTANCE_SKILL

### ISSUE THREAD

**Issue by suggested-username** [Kaseaa/library#10]
[09:44:32.420] [mods] ERROR: Module "library" could not be applied to server connection!
[09:44:32.422] [mods] ERROR: Please contact the module's author: https://github.com/tera-toolbox-mods/library/issues
[09:44:32.426] Error: [dispatch] [library] hook: Error: no definition found for message (name: "C_START_INSTANCE_SKILL", code: 21264, version: 8)
    at Dispatch.createHook (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch.js:230:27)
    at Dispatch.hook (C:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch.js:265:27)
    at NetworkModInterface.hook (C:\TeraToolbox\bin\mod.js:280:36)
    at new player (C:\TeraToolbox\mods\library\class\player.js:334:132)
    at Library.loadAllModules (C:\TeraToolbox\mods\library\index.js:25:24)
    at new Library (C:\TeraToolbox\mods\library\index.js:35:57)
    at new Require (C:\TeraToolbox\mods\library\index.js:44:9)
    at Mod.loadNetworkInstance (C:\TeraToolbox\bin\mod.js:595:31)
    at ModManager.loadNetwork (C:\TeraToolbox\bin\mod-manager.js:252:20)
    at C:\TeraToolbox\bin\mod-manager.js:233:22

**Comment by Kasea** [comment]
toolbox issue, the new def will be added later today
